version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LN_SWAP_FRONTEND_IP}
      APP_PORT: 5173
      PROXY_AUTH_ADD: "false"

  redis:
    image: redis:latest
    command:
      - redis-server
      - redis.conf
      - --requirepass
      - ${REDIS_PASS}
      - --appendonly yes
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

  frontend:
    image: jaonoctus/lightning-swap-frontend:latest@sha256:8b83fede26b05299197fd20f6f34d79047db748581b975f071bf16ab841f6a19
    environment:
      - VITE_TITLE=LN Swap
    networks:
      default:
        ipv4_address: $APP_LN_SWAP_FRONTEND_IP
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - backend

  backend:
    image: jaonoctus/lightning-swap-backend:latest@sha256:f4bb4a2ede828a9ee2598aa5298f23603cfe8c9565af0b0cc7240ab49c7de73b
    ports:
      - 1536:1536
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS}

      - LND_HOST=${LND_HOST}
      - LND_MACAROON=${LND_MACAROON}

      - SWAP_SERVICE_FEERATE=${SWAP_SERVICE_FEERATE}
      - SWAP_MAX_AMOUNT=${SWAP_MAX_AMOUNT}
      - SWAP_MIN_AMOUNT=${SWAP_MIN_AMOUNT}
      - MIRRORS_TOR_URL=${MIRRORS_TOR_URL}

      - LNBITS_HOST=${LNBITS_HOST}
      - LNBITS_BASE_URL=${LNBITS_BASE_URL}
      - LNBITS_WEBHOOK_URL=${LNBITS_WEBHOOK_URL}
      - LNBITS_MAIN_WALLET_ADMIN_KEY=${LNBITS_MAIN_WALLET_ADMIN_KEY}
      - LNBITS_MAIN_WALLET_INVOICE_KEY=${LNBITS_MAIN_WALLET_INVOICE_KEY}
    networks:
      default:
        ipv4_address: $APP_LN_SWAP_BACKEND_IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${APP_DATA_DIR}/data/backend/database.db:/root/vinci/data/database.db
      - ${APP_DATA_DIR}/.env:/root/vinci/.env
      - ${APP_DATA_DIR}/wallet.json:/root/vinci/data/wallet.json
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - redis

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    depends_on:
      - backend
      - frontend
