#!/bin/bash

UMBREL_HOST=$(echo $(hostname -s 2>/dev/null)".local")

"${UMBREL_ROOT}/scripts/app" start lightning
"${UMBREL_ROOT}/scripts/app" start lnbits
"${UMBREL_ROOT}/scripts/app" compose "${APP_ID}" up --detach tor

echo "App: ${APP_ID} - Generating Tor Hidden Service..."

HIDDEN_SERVICE_FILE="${TOR_DATA_DIR}/app-${EXPORTS_APP_ID}/hostname"
if [[ -f "${HIDDEN_SERVICE_FILE}" ]]; then
	exit
fi

for attempt in $(seq 1 100); do
	if [[ -f "${HIDDEN_SERVICE_FILE}" ]]; then
		echo "App: ${APP_ID} - Hidden service file created successfully!"
		break
	fi
	sleep 0.1
done

echo "Waiting for lnbits to be available ..."
for attempt in $(seq 1 500); do
    (curl $LNBITS_URL &> /dev/null)
    if [[ "$?" -eq 0 ]]; then
        break
    fi
    sleep 0.1
done

(curl $LNBITS_URL &> /dev/null)
if [[ ! "$?" -eq 0 ]]; then
    echo "Lnbits not available."
    exit
fi

echo "Lnbits is available."

tor_hidden_service=$(cat $HIDDEN_SERVICE_FILE)
if [ -z ${MIRRORS_TOR_URL+x} ]; then
    export MIRRORS_TOR_URL="http://${tor_hidden_service}"
    echo "MIRRORS_TOR_URL=${MIRRORS_TOR_URL}" >> ${EXPORTS_APP_DIR}/.env
fi

if [[ ! -f "${EXPORTS_APP_DIR}/tor.url" ]]; then
    echo $tor_hidden_service > ${EXPORTS_APP_DIR}/tor.url
fi

LNBITS_URL="http://${UMBREL_HOST}:3007"
export LNBITS_HOST="http://host.docker.internal:3007/api"
export LNBITS_WEBHOOK_URL="http://${APP_LN_SWAP_BACKEND_IP}:${APP_LN_SWAP_BACKEND_PORT}/api/v1/lnbits/webhook"
if [ -z ${LNBITS_MAIN_WALLET_ADMIN_KEY+x} ]; then
    echo "Create a wallet in Lnbits."

    LNBITS_WALLET_URL=$(curl -X GET --head --silent --write-out "%{redirect_url}\n" --output /dev/null "${LNBITS_URL}/wallet?nme=default")
    LNBITS_WALLET_SOURCE=$(curl -L -s -w "\n%{http_code}" "${LNBITS_WALLET_URL}")
    LNBITS_WALLET_KEYS=$(echo $LNBITS_WALLET_SOURCE | python3 -c 'import sys, json, re; print(re.search(r"window\.wallet = ({.*});", sys.stdin.read()).group(1))')

    LNBITS_MAIN_WALLET_ADMIN_KEY=$(echo $LNBITS_WALLET_KEYS | jq .adminkey) 
    LNBITS_MAIN_WALLET_INVOICE_KEY=$(echo $LNBITS_WALLET_KEYS | jq .inkey)

    echo $LNBITS_WALLET_URL > ${EXPORTS_APP_DIR}/lnbits.url
    
    echo "LNBITS_HOST=${LNBITS_HOST}" >> ${EXPORTS_APP_DIR}/.env
    echo "LNBITS_MAIN_WALLET_ADMIN_KEY=${LNBITS_MAIN_WALLET_ADMIN_KEY}" >> ${EXPORTS_APP_DIR}/.env
    echo "LNBITS_MAIN_WALLET_INVOICE_KEY=${LNBITS_MAIN_WALLET_INVOICE_KEY}" >> ${EXPORTS_APP_DIR}/.env
fi